Convert centrallix-sysdoc to using Markdown
LightSys/centrallix pull request #50
Opened 2022-05-09 19:48 UTC by sheesania

2022-05-09 19:51 UTC, sheesania commented
@gbeeley Here are two first passes at converting the centrallix-sysdoc docs to Markdown. I wanted to give you a chance to see how they look before I blow through the rest of the docs.

I'm pretty much just:
- trying to convert the organization of the doc to use Markdown semantic elements like headers
- removing manual line breaks
- adding auto-generated tables of contents
- aiming for the finished doc to look good in plain text or as displayed by GitHub

2022-05-09 19:54 UTC, gbeeley requested changes
Overall this looks good; it would be good to retain outline numbering however where it is present in the original document (1 2 3 ... and/or A B C ... and so forth).

2022-06-10 17:45 UTC, gbeeley requested changes
Great work, we're very close here, I'm impressed re. how nice the tables look.  Just a couple of minor things to fix and this will be ready to merge.  I think there may be a reference to "JSON-REST.txt" in the kardia docs that we'll need to fix separately to refer to JSON-REST.md.

2022-06-10 17:45 UTC, gbeeley commented on centrallix-sysdoc/OSDriver_Overview.md
> +    1.                 O <- F	Local filesystem driver returns the needed content.
Little oddity here -- the numbering has 1. instead of 10. and the O <- F isn't indented right.

2022-06-10 17:45 UTC, gbeeley commented on centrallix-sysdoc/README
> +# Intro
It looks like this needs to be renamed to README.md

2022-06-10 21:55 UTC, merged